# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyDiDi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'BaiduMapKit' #百度地图SDK

  # Pods for MyDiDi

  target 'MyDiDiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyDiDiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
